module(
    name = "unlog",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.13")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "fmt", version = "12.1.0")
bazel_dep(name = "catch2", version = "3.11.0")
bazel_dep(name = "utl", version = "0.1.0")
git_override(
    module_name = "utl",
    commit = "2e774773f6ad569a5c75754bf5e37c32b41bc9eb",
    init_submodules = True,
    remote = "https://github.com/dr7ana/utl",
)

bazel_dep(name = "allocazam", version = "0.1.0")
git_override(
    module_name = "allocazam",
    commit = "9afc67ed45760323f5cd8b91f62dd2eaca8a5d79",
    remote = "https://github.com/dr7ana/allocazam",
)
