module(
    name = "unlog",
    version = "0.1.0",
)

bazel_dep(name = "rules_cc", version = "0.2.20")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "fmt", version = "12.2.0")
bazel_dep(name = "catch2", version = "3.15.1")
bazel_dep(name = "utl", version = "0.1.0")
git_override(
    module_name = "utl",
    commit = "be635551840d172b766cc6d3db0f3defb7d779b4",
    init_submodules = True,
    remote = "https://github.com/dr7ana/utl",
)

bazel_dep(name = "allocazam", version = "0.1.0")
git_override(
    module_name = "allocazam",
    commit = "903eb8d8638cbdf138d77c04632811a7b10e8e9c",
    remote = "https://github.com/dr7ana/allocazam",
)
