module(
    name = "unlog_bench",
    version = "0.1.0",
)

bazel_dep(name = "unlog", version = "0.1.0")
local_path_override(
    module_name = "unlog",
    path = "../",
)

bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_cc", version = "0.2.20")
bazel_dep(name = "rules_python", version = "1.9.0")
bazel_dep(name = "fmt", version = "12.2.0")

git_override(
    module_name = "utl",
    commit = "f4fdcf007fcd647ac831605c6254574e996ad024",
    init_submodules = True,
    remote = "https://github.com/dr7ana/utl",
)

git_override(
    module_name = "allocazam",
    commit = "5cfe98b9274a7cb3c2e04a3f52a5ba2ae0226135",
    remote = "https://github.com/dr7ana/allocazam",
)

http_archive = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.13",
)
use_repo(python, "python_3_13")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.13",
    requirements_lock = "//plot:requirements_lock.txt",
)
use_repo(pip, "pypi")

http_archive(
    name = "benchmark",
    strip_prefix = "benchmark-1.9.4",
    urls = ["https://github.com/google/benchmark/archive/refs/tags/v1.9.4.tar.gz"],
)

http_archive(
    name = "spdlog",
    build_file = "//:spdlog.BUILD.bazel",
    strip_prefix = "spdlog-1.17.0",
    urls = ["https://github.com/gabime/spdlog/archive/refs/tags/v1.17.0.tar.gz"],
)

http_archive(
    name = "quill",
    build_file = "//:quill.BUILD.bazel",
    strip_prefix = "quill-10.2.0",
    urls = ["https://github.com/odygrd/quill/archive/refs/tags/v10.2.0.tar.gz"],
)

http_archive(
    name = "fmtlog",
    build_file = "//:fmtlog.BUILD.bazel",
    strip_prefix = "fmtlog-2.3.0",
    urls = ["https://github.com/MengRao/fmtlog/archive/refs/tags/v2.3.0.tar.gz"],
)
