load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "quill",
    srcs = glob(
        [
            "src/*.cpp",
            "src/**/*.cpp",
        ],
        allow_empty = True,
    ),
    hdrs = glob(
        [
            "include/**/*.h",
            "include/**/*.hpp",
            "quill/**/*.h",
            "quill/**/*.hpp",
            "src/**/*.h",
            "src/**/*.hpp",
        ],
        allow_empty = True,
    ),
    includes = [
        ".",
        "include",
        "src",
    ],
    linkopts = ["-pthread"],
    linkstatic = True,
)
